import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
// import localFont from 'next/font/local'
// import { fontBangla } from '../app/fonts';

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

// export const fontBangla = localFont({
//   // src: "/fonts/mayaboti-normal.ttf",
//   src: "./../fonts/mayaboti-normal.ttf",
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <header className="md:w-11/12 mx-auto">
            <Navbar></Navbar>
          </header>
          <main className="md:w-11/12 mx-auto min-h-[calc(100vh-302px)] bg-base-200">
            {children}
          </main>
          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
